/**
 * THE WEEKLY STUDIES, AND WHAT GOES STALE WHILE THEY DO NOT RUN.
 *
 * The nightly job refreshes the market snapshot. It does not refresh the
 * studies — the replays and grids whose outputs the site quotes as evidence.
 * Those were regenerated by hand, which means they were regenerated when
 * somebody remembered, which means they were not regenerated. On 2026-09-12
 * every file below was between three and four weeks old while the surfaces
 * serving them updated nightly, and nothing anywhere was red.
 *
 * That is the failure dailyPipeline.test.ts was written for, arriving by a
 * different door: there, a generated file was never staged; here, the
 * generator was never invoked. Same outcome — a stale number sitting beside
 * fresh ones, which is the dangerous version, because the fresh ones vouch
 * for it.
 *
 * ── Why this is a list and not a comment in the workflow ──────────────
 *
 * Three things have to agree: the steps that run the generators, the paths
 * the commit step stages, and the gate that checks the stamps moved. Three
 * hand-maintained copies of one fact is how the daily job lost
 * marketContext.json for 26 days. So the fact lives here once, and
 * studyRefresh.test.ts asserts the workflow matches it in both directions.
 *
 * ── The gate is on the stamp, not on the exit code ────────────────────
 *
 * A study that fails soft leaves its old output in place, and a commit step
 * that finds no diff exits 0 and says so cheerfully. The job would be green
 * and the file would be the same age it was. So the check that decides
 * whether this job worked is `assertStampsMoved.ts`: every artefact below
 * must carry a `generatedAt` from THIS run. Not "changed" — a study run on
 * unchanged bars legitimately produces byte-identical output — but stamped
 * within the run window, which is the thing being claimed.
 */

export interface StudyArtifact {
  /** Path under the repository root, exactly as the workflow stages it. */
  repoPath: string;
  /** The script that writes it, exactly as the workflow invokes it. */
  generator: string;
  /** What the site serves from it — i.e. what is wrong while it is stale. */
  serves: string;
}

export const STUDY_ARTIFACTS: readonly StudyArtifact[] = [
  {
    repoPath: "src/data/overnightPremium.json",
    generator: "scripts/research/overnightPremium.ts",
    serves:
      "/api/pretrade and /api/portfolio. This is the evidence for the only method carrying LIVE status in the register, and the API serves it as current.",
  },
  {
    repoPath: "src/data/signalValidation.json",
    generator: "scripts/research/runLab.ts",
    serves:
      "the home page and /validation, where the signal-lab verdicts and their observation counts are quoted as the backtest rung.",
  },
  {
    repoPath: "src/data/touchCalibration.json",
    generator: "scripts/research/touchCalibrationGrid.ts",
    serves: "the reach screen, which prices a level touch off this grid.",
  },
  {
    repoPath: "src/data/equityExecutionStats.json",
    generator: "scripts/backtest/equityReplay.ts",
    serves:
      "/asset/[symbol], and forwardScoring.ts reads it nightly as an input — so a stale replay propagates into a record that is otherwise out of sample.",
  },
  {
    repoPath: "src/data/fingerprintLibrary.json",
    generator: "scripts/backtest/equityReplay.ts",
    serves: "/asset/[symbol], for the analog lookup behind the fingerprint panel.",
  },
];

/**
 * Stale, served, and NOT fixed by this job — with the reason, so the gap is
 * a recorded refusal rather than an oversight.
 *
 * `backtestMetricStats.json` was handed to me as edgeGateReport.ts's output.
 * It is not: edgeGateReport.ts opens that file with `readFileSync` at line
 * 114 and writes nothing at all. The writer is scripts/backtest/report.ts,
 * which is the second stage of `npm run backtest` and reads
 * scripts/backtest/data/ — a gitignored corpus populated by
 * scripts/backtest/fetchHistory.mjs, which refuses to start without
 * COINALYZE_API_KEY. This repository's Actions runner has no such secret, so
 * adding the step would produce a soft failure every week and then a hard
 * gate failure behind it: a red job that reports a missing key as if it were
 * a broken study.
 *
 * The same corpus is why the other three files below are also frozen at
 * 2026-08-15. They are one blocked dependency, not four separate ones.
 */
export interface UnrefreshedArtifact {
  repoPath: string;
  generator: string;
  blockedBy: string;
}

export const BLOCKED_ON_BACKTEST_CORPUS: readonly UnrefreshedArtifact[] = [
  { repoPath: "src/data/backtestMetricStats.json", generator: "scripts/backtest/report.ts", blockedBy: "COINALYZE_API_KEY" },
  { repoPath: "src/data/backtestResearch.json", generator: "scripts/backtest/report.ts", blockedBy: "COINALYZE_API_KEY" },
  { repoPath: "src/data/backtestStats.json", generator: "scripts/backtest/report.ts", blockedBy: "COINALYZE_API_KEY" },
  { repoPath: "src/data/historicalFingerprints.json", generator: "scripts/backtest/report.ts", blockedBy: "COINALYZE_API_KEY" },
  { repoPath: "src/data/executionStats.json", generator: "scripts/backtest/executionReport.ts", blockedBy: "COINALYZE_API_KEY" },
];

/** Distinct scripts to invoke, in manifest order, each named once. */
export function studyGenerators(): string[] {
  return [...new Set(STUDY_ARTIFACTS.map((a) => a.generator))];
}
