import { describe, expect, it } from "vitest";
import calibrationJson from "@/data/touchCalibration.json";
import { CalibrationCell, EFFECT_SOUGHT_PP, conversionReport, nearestCell } from "./touchCalibration";

/**
 * These are INVARIANT tests, not value tests.
 *
 * The grid behind this module is regenerated by
 * scripts/research/touchCalibrationGrid.ts, so pinning "the 21/10 cell is
 * -1.541pp" would break on every legitimate rerun and teach whoever reruns
 * it to update the expectation without reading it. What must hold across
 * ANY regeneration is that the charged figures govern, and that the number
 * a caller parses agrees with the sentence printed beside it.
 *
 * The second of those is not hypothetical. Before the fix these tests
 * lock in, the 10d/20% cell returned the sentence "no detectable bias ...
 * the honest answer here is a null" with `bias_pp: -0.366` in the field
 * next to it — a value below its own 0.427pp floor.
 */

const cells = (calibrationJson as unknown as { cells: CalibrationCell[] }).cells;

/** Every measured cell, addressed the way a caller would address it. */
const everyCell = cells.map((c) => [c.horizon_sessions, c.barrier_pct, c] as const);

describe("touchCalibration grid shape", () => {
  it("has cells to report on", () => {
    expect(cells.length).toBeGreaterThan(0);
  });

  it.each(everyCell)("%i/%i%% charges the serial correlation in the conservative direction", (_h, _b, cell) => {
    for (const stat of [cell.trailing, cell.in_window]) {
      // Inflation is a multiplier on the SE; it may be exactly 1 (no positive
      // ar1 found) but must never shrink the floor or inflate significance.
      expect(stat.ar1_inflation).toBeGreaterThanOrEqual(1);
      expect(stat.mde_pp_adjusted).toBeGreaterThanOrEqual(stat.mde_pp);
      expect(Math.abs(stat.t_adjusted)).toBeLessThanOrEqual(Math.abs(stat.t) + 1e-9);
    }
  });

  it.each(everyCell)("%i/%i%% reports blocks as worth no more than their headcount", (_h, _b, cell) => {
    expect(cell.trailing.effective_blocks).toBeLessThanOrEqual(cell.blocks);
    expect(cell.trailing.effective_blocks).toBeGreaterThan(0);
  });

  it.each(everyCell)("%i/%i%% judges `resolves` on the adjusted floor, not the raw one", (_h, _b, cell) => {
    expect(cell.resolves).toBe(cell.trailing.mde_pp_adjusted <= EFFECT_SOUGHT_PP);
  });
});

describe("conversionReport", () => {
  it("returns the exact cell when one exists and says so", () => {
    const c = cells[0];
    const r = conversionReport(c.horizon_sessions, c.barrier_pct)!;
    expect(r.measured_at.exact_match).toBe(true);
    expect(r.measured_at.horizon_sessions).toBe(c.horizon_sessions);
    expect(r.measured_at.barrier_pct).toBe(c.barrier_pct);
  });

  it("answers an unmeasured request from the nearest cell and flags the substitution", () => {
    // 7 sessions / 12% is on no grid line. The caller still gets an answer,
    // but must be able to see that a different cell answered it.
    const r = conversionReport(7, 12)!;
    expect(r.measured_at.exact_match).toBe(false);
    expect(cells.some((c) => c.horizon_sessions === r.measured_at.horizon_sessions && c.barrier_pct === r.measured_at.barrier_pct)).toBe(true);
  });

  it("quotes the ADJUSTED floor as the noise floor", () => {
    for (const [h, b, cell] of everyCell) {
      expect(conversionReport(h, b)!.noise_floor_pp).toBe(cell.trailing.mde_pp_adjusted);
    }
  });

  it("reports what the blocks are worth, never the raw count alone", () => {
    for (const [h, b, cell] of everyCell) {
      const r = conversionReport(h, b)!;
      expect(r.blocks).toBe(cell.blocks);
      expect(r.effective_blocks).toBe(cell.trailing.effective_blocks);
    }
  });

  /**
   * THE REGRESSION THIS FILE EXISTS FOR.
   *
   * A caller that reads `bias_pp` and never reads `verdict` must not be
   * handed a figure the verdict disowns.
   */
  it("withholds bias_pp wherever the estimate does not clear its own floor", () => {
    for (const [h, b, cell] of everyCell) {
      const r = conversionReport(h, b)!;
      const clears = Math.abs(cell.trailing.t_adjusted) >= 2;
      if (!clears || !cell.resolves) {
        expect(r.bias_pp, `${h}/${b}% offered a bias it cannot support`).toBeNull();
      } else {
        expect(r.bias_pp).toBe(cell.trailing.symmetric_pp);
      }
    }
  });

  it("never says 'no detectable bias' while also returning one", () => {
    for (const [h, b] of everyCell) {
      const r = conversionReport(h, b)!;
      if (/No detectable bias/.test(r.verdict)) {
        expect(r.bias_pp, `${h}/${b}% contradicts its own verdict`).toBeNull();
      }
    }
  });

  it("decides on the charged t, and discloses when the uncharged one disagreed", () => {
    const flipped = cells.filter(
      (c) => Math.abs(c.trailing.t) >= 2 && Math.abs(c.trailing.t_adjusted) < 2
    );
    // If a regeneration ever leaves no such cell this test is vacuous rather
    // than wrong — but on the committed grid four cells flip, and the
    // disclosure is the whole point of keeping the uncharged t in the type.
    for (const c of flipped) {
      const r = conversionReport(c.horizon_sessions, c.barrier_pct)!;
      expect(r.verdict).toContain("No detectable bias");
      expect(r.verdict).toContain("uncharged t");
      expect(r.bias_pp).toBeNull();
    }
  });

  it("does not describe the blocks as independent periods", () => {
    // The design absorbs correlation BETWEEN NAMES, not between blocks. Copy
    // claiming N independent periods overstated the sample by up to 1.81x.
    for (const [h, b] of everyCell) {
      const r = conversionReport(h, b)!;
      expect(r.method).not.toMatch(/independent periods/i);
      expect(r.verdict).not.toMatch(/independent periods/i);
    }
  });

  it("names the drift component so it is never mistaken for the bias", () => {
    for (const [h, b, cell] of everyCell) {
      const r = conversionReport(h, b)!;
      expect(r.drift_component_pp).toBe(cell.antisymmetric_trailing_pp);
      expect(r.method).toMatch(/ANTISYMMETRIC/);
      expect(r.method).toMatch(/DRIFT/);
    }
  });
});

describe("nearestCell", () => {
  it("scores in log space so a 2x error in either axis is treated alike", () => {
    // 10 sessions is as far from 5 as 20 sessions is, proportionally.
    const grid = new Set(cells.map((c) => `${c.horizon_sessions}/${c.barrier_pct}`));
    const found = nearestCell(1000, 1000);
    expect(found).not.toBeNull();
    expect(grid.has(`${found!.cell.horizon_sessions}/${found!.cell.barrier_pct}`)).toBe(true);
    expect(found!.exact).toBe(false);
  });
});
