import Link from "next/link";
import {
  FamilyBreadthSummary,
  Outcome,
  RowDecomposition,
  buildValidationReport,
} from "@/lib/validation/buildValidationReport";
import labJson from "@/data/signalValidation.json";
import metricStats from "@/data/backtestMetricStats.json";
import ivRvJson from "@/data/ivRvHistory.json";
import paperJson from "@/data/paperLines.json";
import { metricWeight, restatedRead } from "@/lib/signals/scoring";
import { ResolutionSchedule } from "@/components/validation/ResolutionSchedule";
import { ScreenKillLine } from "@/components/validation/ScreenKillLine";
import { evaluateIvRvScreen } from "@/lib/research/ivRvScreen";
import type { IvRvPoint } from "@/lib/research/ivRv";
import { EvidenceLadder } from "@/components/validation/EvidenceLadder";
import { ForwardRecord } from "@/components/validation/ForwardRecord";
import forwardVerdictJson from "@/data/forwardVerdictRecord.json";
import { ForwardVerdictRecord } from "@/lib/research/forwardVerdict";
import { LiveFills, PaperBook } from "@/components/validation/PaperBook";
import { PaperLinesArtifact, buildPaperBook } from "@/lib/validation/paperBook";
import liveLedgerJson from "@/data/liveLedger.json";
import { LiveLedger } from "@/lib/validation/roundTrips";
import type { ResolutionSchedule as Schedule } from "@/lib/research/ivRvSchedule";

/**
 * THE AUDIT — every signal measured, including the ones that failed.
 *
 * Roadmap Phase 3's exit criterion, and built BEFORE the next wave of
 * signals: a platform that cannot show its existing failures has no business
 * adding candidates.
 *
 * The headline number is deliberately unflattering. Competitors publish the
 * indicators that worked; the only durable thing here is the record that
 * includes the ones that did not — and a survival rate this low is what makes
 * the survivors worth anything.
 *
 * ── The page is ordered by TIER, weakest-looking evidence last ────────
 *
 * It used to open with "8 of 24 measured signals clear their own bar" — a
 * true sentence about the one tier whose numbers were computed on the data
 * that chose the signals. Leading with it invited a reader to average three
 * incomparable kinds of evidence into one impression, and the tier with the
 * biggest n and the greenest figures would have dominated that average.
 *
 * So: ladder, then paper book, then the collector still on its clock, then
 * the empty live tier, and the lab last with its own headline attached to it
 * rather than to the page.
 *
 * ── One unit, and where it deliberately stops ─────────────────────────
 *
 * Basis points for everything in RETURN space, so a paper line and a
 * decomposition column can be held against each other. Win rate and the
 * breakeven cost charge are in WIN-RATE space and are not converted: a win
 * rate has no basis-point value without a payoff distribution, and inventing
 * one to make the columns match would be a worse error than the mismatch. The
 * lab section says so where a reader would otherwise assume.
 */

export const metadata = { title: "Validation — Leverage Terminal" };

const report = buildValidationReport({
  lab: labJson as Parameters<typeof buildValidationReport>[0]["lab"],
  moduleGrades: metricStats.moduleGrades as Parameters<typeof buildValidationReport>[0]["moduleGrades"],
  moduleBreadth: metricStats.moduleBreadth as Parameters<typeof buildValidationReport>[0]["moduleBreadth"],
});

/*
 * The IV/RV collector, read straight off the artefact the nightly job writes.
 * Both `schedule` and `reading` are generated by `buildIvRvHistory` from the
 * same counts, so nothing here recomputes a statistic — the page renders what
 * the projection concluded rather than forming its own opinion, which is the
 * charter's one-engine rule applied to a surface that could easily have
 * re-derived "is it resolved yet" a second, drifting way.
 */
const ivRv = ivRvJson as unknown as {
  schedule: Schedule;
  reading: string;
  coverage: { joined: number };
  observationSessions: Array<{ date: string; sessionIndex: number }>;
  points: IvRvPoint[];
};
const ivRvDates = [...new Set(ivRv.points.map((p) => p.date))].sort();
const ivRvSymbols = new Set(ivRv.points.map((p) => p.symbol)).size;

/*
 * The panel calendar, carried by the artefact rather than reconstructed here.
 * The forward horizon is counted in SESSIONS, and inferring session distance
 * from calendar-day gaps is precisely how the independent-window gate would
 * come out looking met when it is not.
 */
const ivRvSessionIndex = new Map(ivRv.observationSessions.map((o) => [o.date, o.sessionIndex]));
const screenStanding = evaluateIvRvScreen(ivRv.points, (d) => ivRvSessionIndex.get(d));

/*
 * The register of declared strategies. Reshaped, never recomputed — every
 * statistic below is the paper engine's, and the display layer's only jobs are
 * to classify a half of a record as backtest or paper and to pair each figure
 * with the sample size behind it.
 */
const paperBook = buildPaperBook(paperJson as unknown as PaperLinesArtifact);
const liveLedger = (liveLedgerJson as unknown as { ledger: LiveLedger }).ledger;
const forwardVerdict = forwardVerdictJson as unknown as ForwardVerdictRecord;

const GROUPS: Array<{ outcome: Outcome; title: string; blurb: string; tone: string }> = [
  {
    outcome: "cleared",
    title: "Cleared the bar",
    tone: "text-success",
    blurb:
      "Beat its own baseline after costs AND survived correction for multiple testing. Clearing the bar is NOT the " +
      "same as being used: several of these are supporting variants of the one that ships, and one is explicitly " +
      "withheld. The rows marked IN USE are the only results anything on this site actually reads.",
  },
  {
    outcome: "below",
    title: "Measured worse than its own null",
    tone: "text-danger",
    blurb:
      "Not merely unproven — these read BELOW the baseline they were tested against. That is the strongest kind of " +
      "negative result and the most useful, because it says the intuition points the wrong way rather than nowhere.",
  },
  {
    outcome: "indistinct",
    title: "Cannot be told apart from chance",
    tone: "text-amber",
    blurb:
      "Measured honestly and came back inside the noise. Some are significant before costs and stop being so after " +
      "them, which is the distinction between detectable and tradeable.",
  },
  {
    outcome: "unmeasured",
    title: "Never measured",
    tone: "text-ink-faint",
    blurb:
      "No historical source exists to test these against, so no verdict is claimed. This is a statement about OUR " +
      "data, not about the signal — they are displayed as context and are never permitted to vote.",
  },
];

/**
 * A win RATE — the share of periods won. Not a return, and deliberately still
 * rendered in percent so it cannot be mistaken for one of the bp figures.
 */
function pct(v: number | null): string {
  return v === null ? "—" : `${v.toFixed(1)}%`;
}

/**
 * A return, in basis points. The one unit shared with the paper book.
 *
 * The decomposition stores percent because that is what the research layer
 * computes in; the conversion happens once, here, at the boundary. Doing it in
 * the research layer would change every number in `signalValidation.json` for
 * a presentation reason, and doing it per-call-site is how three of four
 * documented spreads in this repository ended up 10x low.
 */
function signedBp(pctValue: number): string {
  const v = pctValue * 100;
  return `${v >= 0 ? "+" : ""}${v.toFixed(1)}bp`;
}

/**
 * THE THREE COLUMNS THAT SEPARATE PICKING FROM POOL DRIFT.
 *
 * The win rate above answers "does the ranking beat its own universe". It
 * cannot answer "should I buy this instead of the index", and those have
 * opposite trading implications: a signal that picks the best names in a pool
 * which itself trailed the benchmark is a real finding about the ranking and
 * a bad reason to put money on it.
 *
 * All three are rendered, always, including when the middle row is the
 * unflattering part. Showing only the third would let the pool's drift be
 * read as the signal's skill.
 */
function Decomposition({ d }: { d: RowDecomposition }) {
  const rows = [
    { c: d.selection, note: "the ranking's own contribution" },
    { c: d.poolDrift, note: `whether the panel beat ${d.benchmark} regardless of the ranking` },
    { c: d.versusIndex, note: "the only column that pays" },
  ];
  return (
    <details className="rounded-md border border-line/60 bg-surface/40">
      <summary className="cursor-pointer px-3 py-2 text-[11px] text-ink-muted">
        <span className="uppercase tracking-[0.12em] text-ink-faint">vs {d.benchmark}</span>{" "}
        <span className="font-mono text-ink">{signedBp(d.versusIndex.meanPct)}</span>{" "}
        <span className="text-ink-faint">
          per period (n={d.versusIndex.n}), of which {signedBp(d.poolDrift.meanPct)} is the pool
        </span>
      </summary>
      <div className="flex flex-col gap-2 px-3 pb-3">
        <table className="w-full font-mono text-[11px]">
          <tbody>
            {rows.map(({ c, note }) => (
              <tr key={c.label} className="align-top">
                <td className="py-0.5 pr-3 text-ink-muted">{c.label}</td>
                <td className="py-0.5 pr-3 text-right text-ink">{signedBp(c.meanPct)}</td>
                {/*
                  n on every row rather than once in the footer. The three
                  columns are computed on the same inner join and should agree
                  — printing each one is what would make it visible the day one
                  of them stops agreeing.
                */}
                <td className="py-0.5 pr-3 text-right text-ink-faint">n={c.n}</td>
                <td className="py-0.5 pr-3 text-right text-ink-muted">t={c.t.toFixed(2)}</td>
                {/*
                  The smallest effect this sample could have resolved. Without
                  it a small number reads as "no effect" when the test could
                  never have seen one.
                */}
                <td className="py-0.5 pr-3 text-right text-ink-faint">
                  resolves ≥{(c.detectablePctAtT3 * 100).toFixed(1)}bp
                </td>
                <td className="py-0.5 font-sans text-ink-faint">{note}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <p className="text-[11px] leading-relaxed text-ink-muted">{d.reading}</p>
        {/*
          The benchmark's history is shorter than the panel's, so these three
          columns describe FEWER periods than the win rate above. Saying so is
          the difference between one sample and two presented as one.
        */}
        <p className="text-[10px] leading-relaxed text-ink-faint">
          {d.n} periods, {d.fromDate} to {d.toDate} — the span {d.benchmark} covers, which is shorter
          than the window behind the win rate above. Each column is a mean of per-period
          differences over exactly these dates, so the first two add to the third.
        </p>
      </div>
    </details>
  );
}

/**
 * WHAT "12 DECLARED HYPOTHESES" IS WORTH.
 *
 * The headcount is the strongest anti-data-mining claim on this page: it says
 * the survivors cleared a bar raised for every idea tried, not just the ones
 * that worked. That claim is real, and it is smaller than it sounds — the
 * regime-gated variants are their parent's own numbers split by date, so they
 * come back correlated at 1.000 and the twelve are worth two or three.
 *
 * Rendered in muted type rather than as a warning, deliberately. This does
 * not invalidate anything above it: correcting across twelve correlated tests
 * is STRICTER than correcting across three, so every survivor cleared a
 * harder bar than it strictly had to. What shrinks is the coverage claim, and
 * a red box would say the opposite of that.
 *
 * Used by both families. On the equity hypotheses the effective and distinct
 * counts agree; on the crypto modules they are 8.5 and 3.0, so the second
 * figure appears only where it disagrees — printing "8.5 effective, 8.5
 * distinct" everywhere would train a reader to skip the line that matters.
 */
/**
 * Which members of a duplicate pair have been silenced in the composite.
 *
 * Derived from metricWeight/restatedRead rather than named here: the equity
 * family renders through this same component and has no muted members, so a
 * hand-written sentence would have to be suppressed for one family and would
 * go stale for the other.
 */
function mutedMembers(pairs: FamilyBreadthSummary["duplicatePairs"]): string[] {
  const muted = new Set<string>();
  for (const d of pairs) {
    for (const id of [d.a, d.b]) {
      if (restatedRead(id) !== null && metricWeight(id) === 0) muted.add(id);
    }
  }
  return [...muted];
}

function FamilyBreadthNote({ b, label }: { b: FamilyBreadthSummary; label: string }) {
  /*
   * Half a bet of slack before the counting figure is shown at all. Signed and
   * absolute rho differ slightly on any family with a mildly negative pair,
   * and surfacing a 0.1 gap as a second headline number invents a
   * disagreement out of rounding.
   */
  const diverges =
    b.distinctTests !== null && b.effectiveBets !== null && b.distinctTests < b.effectiveBets - 0.5;
  return (
    <div className="mt-3 rounded-md border border-line/60 bg-surface/40 px-3 py-2">
      <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
        <span className="text-[10px] uppercase tracking-[0.12em] text-ink-faint">{label}</span>
        <span className="font-mono text-[11px] text-ink">
          {b.effectiveBets === null ? "unmeasured" : `${b.effectiveBets.toFixed(1)} effective`}
          {b.otherEndBets !== null && b.effectiveBets !== null && b.otherEndBets !== b.effectiveBets
            ? `–${b.otherEndBets.toFixed(1)}`
            : ""}
        </span>
        {/*
          The counting answer, in amber, because where it appears it is the
          figure a multiple-testing claim has to use — and it is the smaller
          of the two, so the muted-grey treatment given to the bets figure
          would leave the more generous number reading as the conclusion.
        */}
        {diverges && (
          <span className="font-mono text-[11px] text-amber">
            {b.distinctTests!.toFixed(1)} distinct ideas
          </span>
        )}
        <span className="font-mono text-[11px] text-ink-faint">
          mean pairwise rho {b.meanPairwiseRho ?? "—"} over {b.pairsMeasured} measurable pairs
        </span>
      </div>
      <p className="mt-1.5 text-[11px] leading-relaxed text-ink-muted">{b.sentence}</p>
      {/*
        The duplicate pairs by name. An aggregate is abstract; "these two rows
        are one row" is what actually stops a reader counting them twice.

        `b.sentence` deliberately does NOT name them — `familyBreadth` keeps
        that clause in its own `duplicateSentence` field, for a JSON reader with
        no table to render. Here the list IS the table, so the prose above it
        would print every pair a second time. What the list cannot say on its
        own is what a 1.000 MEANS, so that one line is stated here, from the
        rows themselves rather than passed through as text.
      */}
      {b.duplicatePairs.length > 0 && (
        <>
          <p className="mt-1.5 text-[11px] leading-relaxed text-ink-muted">
            {b.duplicatePairs.every((d) => Math.abs(d.rho) >= 0.999)
              ? "These are not similar tests. Each pair is one series measured twice:"
              : "These pairs move together closely enough to count as one test, not two:"}
          </p>
          <ul className="mt-1 flex flex-col gap-0.5 font-mono text-[10px] text-ink-faint">
            {b.duplicatePairs.map((d) => (
              <li key={`${d.a}/${d.b}`}>
                {/* ≡ for a duplicate, ≡− for one that is the other negated. The
                    sign is the whole difference between "we tested this twice"
                    and "we tested this twice and called the second one a
                    disagreement", so it cannot be dropped from the glyph. */}
                {d.a} {d.rho < 0 ? "≡−" : "≡"} {d.b} · rho {d.rho.toFixed(3)}
              </li>
            ))}
          </ul>
          {/*
            What the ENGINE does about them, read from the engine rather than
            written here so this line cannot outlive the fix it describes.
            Without it the list raises an obvious question and answers none of
            it: a reader shown two pairs that are "one series measured twice"
            has every reason to assume the score counts them twice.
          */}
          {mutedMembers(b.duplicatePairs).length > 0 && (
            <p className="mt-1.5 text-[11px] leading-relaxed text-ink-muted">
              Counted once in the score: {mutedMembers(b.duplicatePairs).join(" and ")}{" "}
              {mutedMembers(b.duplicatePairs).length === 1 ? "carries" : "carry"} no weight in the
              composite, so each pair votes through one member only. Still measured here — a retired
              vote is not a deleted measurement, which is why the pair prints above at all.
            </p>
          )}
        </>
      )}
    </div>
  );
}

export default function ValidationPage() {
  const survival = report.totals.measured > 0 ? (report.totals.cleared / report.totals.measured) * 100 : 0;

  return (
    <div className="min-h-screen">
      <main className="mx-auto flex max-w-[1000px] flex-col gap-5 px-4 py-6 sm:px-6">
        <div className="flex flex-wrap items-baseline justify-between gap-3">
          <div>
            <h1 className="text-lg font-semibold tracking-tight text-ink">Validation</h1>
            <p className="mt-0.5 text-[11px] uppercase tracking-[0.16em] text-ink-faint">
              Every signal measured · failures included
            </p>
          </div>
          <nav className="flex gap-4 text-[11px] uppercase tracking-[0.16em] text-ink-muted">
            <Link href="/" className="hover:text-ink">
              ← Brief
            </Link>
            <Link href="/intelligence" className="hover:text-ink">
              Intelligence
            </Link>
          </nav>
        </div>

        <EvidenceLadder
          labMeasured={report.totals.measured}
          labCleared={report.totals.cleared}
          registered={paperBook.totals.registered}
          withPaperRecord={paperBook.totals.withPaperRecord}
          clearingOutOfSample={paperBook.totals.clearing}
          liveTrips={liveLedger.trips}
          liveJoinable={liveLedger.joinable}
          verdictResolved={forwardVerdict.totals.resolved}
          verdictOpen={forwardVerdict.totals.open}
        />

        {/*
          Rung 2, and FIRST on it, because it is the site's own published word
          rather than a hypothesis the site is testing. It also has no numbers
          yet, which puts it first under the page's own ordering rule: the
          strongest-looking figures are the ones you reach last.
        */}
        <ForwardRecord record={forwardVerdict} />

        {/* Rung 2, and the only rung with numbers that were not chosen on their own data. */}
        <PaperBook book={paperBook} />

        {/*
          The criterion BEFORE the data, and directly above the collector whose
          rows will decide it. The first forward legs resolve within days; a
          reclassification rule published after they land is not a rule, it is
          a description. It sits above the schedule because a reader should
          meet the test before meeting the sample.
        */}
        <ScreenKillLine standing={screenStanding} />

        {/*
          Placed above the measured signals rather than at the bottom with the
          unmeasured ones. It is not "never measured" — it is measured on a
          clock, and the clock is the finding. Burying it would recreate the
          exact ambiguity it exists to remove.
        */}
        <ResolutionSchedule
          schedule={ivRv.schedule}
          reading={ivRv.reading}
          symbols={ivRvSymbols}
          observationSessions={ivRvDates.length}
          firstObservation={ivRvDates[0] ?? null}
          lastObservation={ivRvDates[ivRvDates.length - 1] ?? null}
        />

        {/* Rung 3. Empty, and rendered so that its emptiness is a measurement. */}
        <LiveFills ledger={liveLedger} />

        {/*
          Rung 1, last, with its headline attached to IT rather than to the
          page. "8 of 24 clear their own bar" is a claim about the lab, and the
          lab's numbers were computed on the history that chose the signals.
          As the page's opening line it was read as a claim about the site.
        */}
        <section className="rounded-xl border border-hairline bg-panel/60 px-5 py-5 sm:px-6">
          <div className="flex flex-wrap items-baseline gap-x-3">
            <h2 className="text-[13px] font-semibold uppercase tracking-[0.14em] text-ink">
              Signal lab — the backtest rung
            </h2>
            <span className="font-mono text-[11px] text-ink-faint">n={report.totals.measured}</span>
          </div>
          <p className="mt-2 text-2xl font-bold leading-tight text-ink">
            {report.totals.cleared} of {report.totals.measured} measured signals clear their own bar.
          </p>
          <p className="mt-2 max-w-3xl text-[13px] leading-relaxed text-ink-muted">
            That is a {survival.toFixed(0)}% survival rate, and it is the point rather than an apology. Anyone can
            publish the indicators that worked. The record below includes every one that did not, with the criteria
            that would have killed it written down before it was run — which is the only reason the survivors are
            worth anything.
          </p>
          {/*
            The unit warning, stated where the change of unit happens. Above
            this line every return is in basis points; below it, win rates and
            cost charges are in percentage points of WIN RATE, which is a
            different space and cannot be converted without a payoff
            distribution nobody has estimated.
          */}
          <p className="mt-3 rounded-md border border-line/60 bg-surface/40 px-3 py-2 text-[11px] leading-relaxed text-ink-muted">
            <span className="uppercase tracking-[0.12em] text-ink-faint">Change of unit</span> · Win
            rate and the breakeven cost charge below are in percentage points of WIN RATE, not
            return. They are not comparable with the basis-point figures above and are not
            converted, because a win rate has no basis-point value without a payoff distribution.
            The per-period returns inside each row&rsquo;s benchmark decomposition ARE returns, and
            those are quoted in basis points like everything else.
          </p>
          <p className="mt-3 text-[11px] leading-relaxed text-ink-faint">
            Each row shows the cost charge at which it would stop clearing. The verdict answers yes-or-no at the
            declared {report.costPp}pp; the breakeven answers how wrong that assumption would have to be. Two
            signals sharing a verdict with breakevens of 2.4pp and 5.4pp are entirely different propositions, and
            a rebalance running four times as often should be charged four times as much.{" "}
            The equity study corrected across all {report.equityFamilySize} declared hypotheses at once on{" "}
            {report.equityInstruments} instruments, charging {report.costPp}pp of costs to every one. Correcting only
            across survivors would undo the correction. A further {report.totals.unmeasured} modules have never been
            measured at all and are listed at the bottom rather than quietly omitted.
          </p>

          {/*
            HOW MANY IDEAS THAT HEADCOUNT IS. Placed directly under the
            sentence that quotes the headcount, because the two are one claim
            and separating them is how "12 declared hypotheses" gets read as a
            broad search. The panel above already learned this lesson about a
            table of miners; this is the same arithmetic on a table of tests.
          */}
          {report.equityFamilyBreadth && (
            <FamilyBreadthNote b={report.equityFamilyBreadth} label="How many ideas that is" />
          )}

          {/*
            The same measurement on the crypto modules, and it does not come
            back the same. Kept as its own block rather than averaged in with
            the equity one: the two families are corrected separately, so a
            combined breadth figure would describe a correction nobody ran.

            It is the crypto family, not the equity one, that makes the whole
            measurement worth having. There the two counts agree and the note
            is a footnote; here they disagree threefold, because two module
            pairs are one series measured twice — and one of those pairs is
            inverted, which the effective-bets figure scores as extra
            diversification. See src/lib/research/moduleBreadth.ts.
          */}
          {report.cryptoFamilyBreadth && (
            <FamilyBreadthNote
              b={report.cryptoFamilyBreadth}
              label="How many ideas the crypto modules are"
            />
          )}
        </section>

        {GROUPS.map((group) => {
          const rows = report.rows.filter((r) => r.outcome === group.outcome);
          if (rows.length === 0) return null;
          return (
            <section key={group.outcome} className="rounded-xl border border-hairline bg-panel/40 px-5 py-4 sm:px-6">
              <div className="flex flex-wrap items-baseline gap-x-3">
                <h2 className={`text-[13px] font-semibold uppercase tracking-[0.14em] ${group.tone}`}>
                  {group.title}
                </h2>
                <span className="font-mono text-[11px] text-ink-faint">
                  {rows.length} signal{rows.length === 1 ? "" : "s"}
                </span>
              </div>
              <p className="mt-1.5 max-w-3xl text-[12px] leading-relaxed text-ink-muted">{group.blurb}</p>

              <ul className="mt-3 flex flex-col divide-y divide-hairline">
                {rows.map((r) => (
                  <li key={`${r.family}-${r.id}`} className="flex flex-col gap-1.5 py-3">
                    <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
                      <span className="font-mono text-[13px] text-ink">{r.id}</span>
                      <span className="text-[10px] uppercase tracking-[0.12em] text-ink-faint">{r.family}</span>
                      {r.inUse && (
                        <span className="rounded border border-success/30 px-1.5 py-0.5 text-[9px] uppercase tracking-[0.12em] text-success">
                          in use
                        </span>
                      )}
                      {r.retiredBy && (
                        <span className="rounded border border-amber/25 px-1.5 py-0.5 text-[9px] uppercase tracking-[0.12em] text-amber">
                          retired by {r.retiredBy}
                        </span>
                      )}
                    </div>

                    {/*
                      n rides beside each rate rather than sitting once at the
                      end of the row. A win rate and its lower bound come from
                      the same sample, so repeating it looks redundant — right
                      up until a row appears whose bound was computed on fewer
                      periods than its rate, which is exactly the kind of thing
                      a single trailing `n` hides.
                    */}
                    <div className="flex flex-wrap gap-x-5 gap-y-1 font-mono text-[11px] text-ink-muted">
                      <span>
                        <span className="text-ink-faint">win</span> {pct(r.winRatePct)}{" "}
                        <span className="text-ink-faint">n={r.n ?? "—"}</span>
                      </span>
                      <span>
                        <span className="text-ink-faint">95% floor</span> {pct(r.lowerBoundPct)}{" "}
                        <span className="text-ink-faint">n={r.n ?? "—"}</span>
                      </span>
                      <span>
                        <span className="text-ink-faint">FDR</span> {r.survivesFdr ? "survives" : "no"}
                      </span>
                      {/* The margin the verdict hides. See breakevenCostPp. */}
                      {r.breakevenCostPp !== null && r.breakevenCostPp > 0 && (
                        <span>
                          <span className="text-ink-faint">dies at</span> {r.breakevenCostPp.toFixed(1)}pp costs
                        </span>
                      )}
                    </div>

                    {r.sentence && (
                      <p className="text-[11px] leading-relaxed text-ink-muted">{r.sentence}</p>
                    )}

                    {/* Louder than the verdict, because it outranks it. */}
                    {r.caution && (
                      <p className="rounded-md border border-amber/25 bg-amber/[0.04] px-3 py-2 text-[11px] leading-relaxed text-ink">
                        <span className="font-semibold uppercase tracking-[0.12em] text-amber">Caution</span> ·{" "}
                        {r.caution}
                      </p>
                    )}

                    {r.decomposition && <Decomposition d={r.decomposition} />}

                    {r.killCriteria && (
                      <p className="text-[11px] leading-relaxed text-ink-faint">
                        <span className="text-ink-muted">Declared before the run ·</span> {r.killCriteria}
                      </p>
                    )}
                  </li>
                ))}
              </ul>
            </section>
          );
        })}

        <p className="text-[11px] leading-relaxed text-ink-faint">
          Survivorship runs against every equity result here: the panel is today&rsquo;s instrument list, so names
          that failed and delisted are absent, which flatters a buy-the-winners finding. Treat the printed spreads as
          ceilings. Costs are charged as a flat {report.costPp}pp of win rate rather than modelled per leg, which is
          conservative for the monthly hypotheses and arguably light for the weekly ones.
        </p>
      </main>
    </div>
  );
}
