import { NextResponse } from "next/server";
import overnightJson from "@/data/overnightPremium.json";
import positioningLatestJson from "@/data/positioningLatest.json";
import earningsJson from "@/data/earningsCalendar.json";
import { buildPretrade, BuildInputs, OvernightRow } from "@/lib/pretrade/buildPretrade";
import { EarningsCalendar } from "@/lib/markets/earningsVeto";
import { PositioningPoint } from "@/lib/history/positioningHistory";
import { resolveUniverse } from "@/lib/markets/scannerUniverse";
import { DECLARED_PRICE_EVENTS } from "@/lib/research/corporateActions";
import { CatalystResult, fetchCatalysts } from "@/lib/dossier/providers/edgarCatalysts";
import { fetchVenueStatus } from "@/lib/dossier/providers/tradierStatus";

/**
 * GET /api/pretrade?symbols=APLD,RIOT,CLSK
 *
 * One call, every symbol asked for, no prose and no HTML. Replaces scraping
 * ~30 numbers out of a 235KB server-rendered page — an approach that already
 * broke once when copy changed and silently degraded sixteen validation
 * checks to SKIP.
 *
 * ── Why it reads projections, not the full stores ─────────────────────
 *
 * positioningHistory.json is 6.4MB and grows daily. Parsing it on a cold
 * start to answer a question about one session is the wrong trade for an
 * endpoint whose purpose is speed inside a short window, so this reads
 * positioningLatest.json (~30KB, one row per symbol), regenerated by the same
 * job that writes the history. /api/positioning still serves the full series.
 *
 * ── What is deliberately absent ───────────────────────────────────────
 *
 * `net_edge` and both execution windows are null with reason
 * "no_spread_history" and will stay that way until the spread recorder has
 * twenty sessions in each window. That is not an oversight: the modelled
 * tick cost is wrong by up to two orders of magnitude on these names
 * (Corwin-Schultz returns 114-177bp where the observed book is one tick), and
 * a modelled spread presented as a measured one is how a fictional edge gets
 * published.
 *
 * No verdicts, scores or ratings appear here, and a test asserts their
 * absence structurally.
 */

/*
 * DYNAMIC, and this is load-bearing. Under `force-static` Next evaluates
 * searchParams at BUILD time, so `?symbols=APLD,MARA` was silently ignored
 * and every call returned the whole default universe — caught only by
 * counting the bytes that actually came back. The route reads committed JSON
 * and does no network work, so serving it per-request is cheap.
 */
export const dynamic = "force-dynamic";

/** Cap on symbols per call. Generous, but a request is not a crawl. */
const MAX_SYMBOLS = 50;

export async function GET(req: Request) {
  const url = new URL(req.url);
  const raw = url.searchParams.get("symbols");

  const symbols = raw
    ? [...new Set(raw.split(",").map((s) => s.trim().toUpperCase()).filter(Boolean))]
    : [...resolveUniverse()];

  if (symbols.length === 0) {
    return NextResponse.json(
      { error: "no_symbols", detail: "Pass ?symbols=A,B,C or omit it for the scanner universe." },
      { status: 400 }
    );
  }
  if (symbols.length > MAX_SYMBOLS) {
    return NextResponse.json(
      { error: "too_many_symbols", detail: `At most ${MAX_SYMBOLS} per call; got ${symbols.length}.` },
      { status: 400 }
    );
  }

  const overnight = overnightJson as unknown as { generatedAt: number; rows: OvernightRow[] };
  const positioningLatest = positioningLatestJson as unknown as {
    generatedAt: number;
    points: PositioningPoint[];
  };

  /*
   * Corporate-action counts come from the DECLARED registry rather than from
   * re-running the guard: the raw bars are gitignored and do not exist at
   * request time. This reports what has been judged for each symbol, which is
   * the number a consumer actually needs — how much human judgement its price
   * series is resting on.
   */
  const dataQuality = new Map<string, { adjustments: number; undeclared: number }>();
  for (const symbol of symbols) {
    const declared = DECLARED_PRICE_EVENTS.filter((e) => e.symbol === symbol);
    dataQuality.set(symbol, {
      adjustments: declared.filter((e) => e.treatment === "adjust").length,
      undeclared: 0, // the ingest refuses to write an unjudged step silently
    });
  }

  /*
   * EDGAR is fetched live because after-hours filings are the one input here
   * that cannot be precomputed — they land at any minute after the close and
   * the whole point is catching tonight's. Bounded concurrency out of respect
   * for the SEC's 10-req/s guidance; per-symbol failures degrade to a reason
   * on that symbol rather than failing the call.
   */
  const now = Date.now();
  const catalysts = new Map<string, CatalystResult>();
  const CONCURRENCY = 5;

  /*
   * The venue clock and every top of book cost two requests total regardless
   * of how many symbols were asked for, so it runs alongside the EDGAR sweep
   * rather than after it. With no TRADIER_API_KEY the whole tradability block
   * degrades to "tradier_not_configured" — a stated absence, not a silent one.
   */
  const [venue] = await Promise.all([
    fetchVenueStatus(symbols, now),
    (async () => {
      for (let i = 0; i < symbols.length; i += CONCURRENCY) {
        const batch = symbols.slice(i, i + CONCURRENCY);
        const results = await Promise.all(batch.map((s) => fetchCatalysts(s, now)));
        batch.forEach((s, j) => catalysts.set(s, results[j]));
      }
    })(),
  ]);

  const inputs: BuildInputs = {
    symbols,
    now,
    overnight,
    positioningLatest,
    earnings: earningsJson as unknown as EarningsCalendar,
    // Empty until spreadHistory clears MIN_SPREAD_SESSIONS in both windows.
    measuredRoundTripBp: new Map(),
    dataQuality,
    catalysts,
    venue,
  };

  return NextResponse.json(buildPretrade(inputs));
}
